apiVersion: v1
kind: Service
metadata:
  name: hello-py-svc
spec:
  selector:
    app: hello-py
  ports:
  - protocol: "TCP"
    port: 40000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-py
  name: hello-py
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hello-py
  template:
    metadata:
      labels:
        app: hello-py
    spec:
      containers:
      - image: "mpolawar/hello-py:f219b4b"
        name: hello-py
        ports:
          - containerPort: 5000
